dist: xenial
sudo: required
language: python
python:
  - "3.7"

install:
  - pip install codecov

script:
  - coverage run --source mqtt_translator -m unittest discover -v -s test -p test*.py
  - codecov

after_success:
  - export IMG_VERSION=`date +"%Y.%m.%d"`.$TRAVIS_BUILD_NUMBER
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
  - docker build -t $DOCKER_USERNAME/mqtt-translator:$IMG_VERSION .      
  - docker tag $DOCKER_USERNAME/mqtt-translator:$IMG_VERSION $DOCKER_USERNAME/mqtt-translator:latest
  - docker push $DOCKER_USERNAME/mqtt-translator:$IMG_VERSION
  - docker push $DOCKER_USERNAME/mqtt-translator:latest